### PR TITLE
Deploy

### PR DESCRIPTION
**Pull request by eddiejaoude**

### CODE REVIEW

**Comment by KarenEfereyan** [comment]
Deploy? What did you deploy @eddiejaoude Kindly carry me along pleas

**Comment by eddiejaoude** [comment]
Thanks @KarenEfereyan . Nothing deployed yet, when this PR gets merged, all changes in `develop` branch will go into `main` branch, then other Github Actions using this Action will look to use `main` - so it is not really deployed but available

**Comment by KarenEfereyan** [comment]
What did people do to get their PRs merged

**Comment by eddiejaoude** [comment]
@KarenEfereyan I am not sure what you mean? In this repo or generally?

**Comment by KarenEfereyan** [comment]
@eddiejaoude im seeing some merges. So im wondering if I can make one too.

**Comment by eddiejaoude** [comment]
> What did people do to get their PRs merged

>  im seeing some merges. So im wondering if I can make one too

@KarenEfereyan sorry, I am still not sure what you mean? Could you explain a bit more please

**Comment by jomefavourite** [comment]
What's Github Action?

**Comment by eddiejaoude** [comment]
@jomefavourite it might be better to start a GitHub Discussion on this topic in our `support` repo (plus you will get a green square for starting it too, on your GitHub activity graph on your homepage 😉 ) https://github.com/EddieJaoudeCommunity/support/discussions

I have a GitHub Action video coming out today in a few hours, keep an eye out for it, as it has me building a GitHub Action and also ideas from the community of what it can do 🤓  http://youtube.com/eddiejaoude

**Comment by jomefavourite** [comment]
Okay, I'll keep an eye for the upcoming video.

**Pull request merged**
